# Generated by Django 5.1.6 on 2025-02-13 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_summary', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('source', models.CharField(max_length=200)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news_analyser.keyword')),
            ],
        ),
    ]
