# Generated by Django 5.1.6 on 2025-04-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analyser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='impact_rating',
            field=models.FloatField(default=0),
        ),
    ]
