# Generated by Django 5.1.6 on 2025-04-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analyser', '0003_source_rename_source_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news_analyser.source'),
        ),
    ]
