# Generated by Django 5.1.6 on 2025-11-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_analyser", "0007_alter_userprofile_searches"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="stocks",
            field=models.ManyToManyField(blank=True, to="news_analyser.stock"),
        ),
    ]
