# Generated by Django 5.1.6 on 2025-09-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_analyser", "0007_alter_userprofile_searches"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="keyword",
        ),
        migrations.AddField(
            model_name="news",
            name="keywords",
            field=models.ManyToManyField(
                related_name="news", to="news_analyser.keyword"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="link",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
