# Generated by Django 5.1.6 on 2025-11-19 11:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analyser', '0008_remove_duplicate_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_score', models.FloatField(blank=True, null=True)),
                ('finbert_score', models.FloatField(blank=True, null=True)),
                ('vader_score', models.FloatField(blank=True, null=True)),
                ('textblob_score', models.FloatField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(db_index=True)),
                ('sentiment_label', models.CharField(choices=[('very_negative', 'Very Negative'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('positive', 'Positive'), ('very_positive', 'Very Positive')], max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('analysis_details', models.JSONField(blank=True, default=dict)),
                ('entities', models.JSONField(blank=True, default=list, help_text='Extracted entities (companies, people, locations)')),
                ('keywords_extracted', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(default='ensemble', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at', '-date'], 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='is_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='news_mentions', to='news_analyser.sector'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='news',
            name='tickers',
            field=models.ManyToManyField(blank=True, related_name='news_mentions', to='news_analyser.stock'),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='scrape_frequency',
            field=models.IntegerField(default=30, help_text='Scraping frequency in minutes'),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-published_at', 'source'], name='news_analys_publish_561f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_analyzed'], name='news_analys_is_anal_fe55f2_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-scraped_at'], name='news_analys_scraped_ed575e_idx'),
        ),
        migrations.AddField(
            model_name='sentimentscore',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_scores', to='news_analyser.news'),
        ),
        migrations.AddField(
            model_name='sentimentscore',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_scores', to='news_analyser.sector'),
        ),
        migrations.AddField(
            model_name='sentimentscore',
            name='ticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_scores', to='news_analyser.stock'),
        ),
        migrations.AddIndex(
            model_name='sentimentscore',
            index=models.Index(fields=['ticker', '-created_at'], name='news_analys_ticker__260a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentscore',
            index=models.Index(fields=['sector', '-created_at'], name='news_analys_sector__cb3d20_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentscore',
            index=models.Index(fields=['sentiment_score'], name='news_analys_sentime_45c75a_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentscore',
            index=models.Index(fields=['-created_at'], name='news_analys_created_f3a810_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sentimentscore',
            unique_together={('news', 'sector'), ('news', 'ticker')},
        ),
    ]
